Parameters:
  InstanceType:
    Type: String
    Default: m1.small
    Description: "EC2 instance type, e.g. m1.small, m1.large, etc."
  WebServerPort:
    Type: String
    Default: "80"
    Description: TCP/IP port of the web server
  KeyName:
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access to the web server

Resources:
  myStackWithParams2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/second-sub-stack.yml
      Parameters:
        InstanceType: t1.micro
        KeyName: mykey
