AWSTemplateFormatVersion: "2010-09-09"
Resources:
  myStackWithParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: modules/sub-stack.yml
      Parameters:
        InstanceType: t1.micro
        KeyName: mykey
